[project]
name = "Various scripts for markdown notes"
version = "0.0.1"
authors = [
  { name="Bodey Baker", email="bodeybaker@gmail.com" },
]
description = "Scripts that are used for convenience when writing study notes in markdown."
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.pyright]
exclude = [".git"]
typeshedPaths = [".venv", ".venv/lib/python3.13/site-packages", "typings"]
venvPath = ".venv"
typeCheckingMode = "strict"
